### ISSUE TITLE
How to start following drm-next*

### ISSUE THREAD

**Issue by rmx-it** [FreeBSDDesktop/freebsd-base-graphics#122]
Hi,
the instructions from the Wiki do not work
(for the ports pkg repo) any longer.
So: 
Which base repo to use (drm-next or drm-next-4.7?)

**Comment by nomadlogic** [comment]
Hey there,
I will work on updating the wiki today hopefully, since things have changed quite a bit recently.  I would suggest the following path:

- checkout drm-next
- build world+kernel
-- you will need to ensure llvm39 is installed via pkg prior to this
- install xorg via the standard FreeBSD pkg repository.

The big development is that upstream Xorg has been updated and I can verify it works against drm-next using the Intel DDX.  I have seen issues with modesetting+glamor acceleration but the intel driver seems to be pretty stable at this point.

**Comment by rmx-it** [comment]
Hi,
thanks for your hints!
As it seems, drm-next ist most advanced for AMD/Intel Cards.
But how is the situation for nvidia?

I'm having a quite new HP-Zbook3 with nvidia quaddro I'l like to get working with FreeBSD...

BTW: Whats the preferred input method: evdev?

Thanks anyway for working on the graphics support!

**Comment by nomadlogic** [comment]
You are correct, this repository is to update FreeBSD's DRM support used by Intel and AMD GPU's by getting our code in sync with current Linux kernel implementations.  Nvidia supplies their own DRM implementation for FreeBSD (as well as other critical bits) as part of their binary blob available in the ports/pkgs tree.  It's been a while since I've had an nvidia card but I suspect installing this will be what you are looking for:

http://www.freshports.org/x11/nvidia-driver/
