### ISSUE TITLE
drm permissions with libGL

### ISSUE THREAD

**Issue by mattmacy** [FreeBSDDesktop/freebsd-base-graphics#31]
![img_0326_720](https://cloud.githubusercontent.com/assets/14172449/16133514/26ef42fa-33cd-11e6-869b-a9f6547d6aff.jpg)

**Comment by TheDharc** [comment]
exactly the same here.

**Comment by mattmacy** [comment]
It's missing sysctls that a few apps need. Jean is looking in to it.

**Comment by dumbbell** [comment]
The executed screensaver is simply not allowed to open the device apparently:

```
 1629: openat(AT_FDCWD,"/dev/dri/card0",O_RDWR|O_CLOEXEC,00) ERR#13 'Permission denied'
```

I double check with DTrace to make sure it was not an error returned by the driver, but no, the driver is not called at all.

The screensaver is started with my user ID (who belongs to the `video` group). If I change permission on the device to 666 (instead of the default 660), then it works. When the screensaver (in my test, `/usr/local/bin/xscreensaver-hacks/starwars`) is started manually, it's fine too.

`xscreensaver` has the setuid bit set, I wonder if this affects child processes here.

**Comment by dumbbell** [comment]
Yeah, once the setuid is cleared on `xscreensaver`, it stops complaning.
